"""initial schema with extended store + promo duration

Revision ID: 62139a40f3be
Revises: 
Create Date: 2026-05-22 23:50:12.005549

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '62139a40f3be'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('normalized_brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thc_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thc_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cbd_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cbd_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_dim_products_brand'), 'dim_products', ['brand'], unique=False)
    op.create_index(op.f('ix_dim_products_category'), 'dim_products', ['category'], unique=False)
    op.create_index(op.f('ix_dim_products_normalized_brand'), 'dim_products', ['normalized_brand'], unique=False)
    op.create_index(op.f('ix_dim_products_normalized_name'), 'dim_products', ['normalized_name'], unique=False)
    op.create_table('dim_stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('normalized_store_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('hibuddy_store_id', sa.String(), nullable=True),
    sa.Column('hibuddy_slug', sa.String(), nullable=True),
    sa.Column('hours_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_company', sa.String(), nullable=True),
    sa.Column('agco_licence_number', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_dim_stores_agco_licence_number'), 'dim_stores', ['agco_licence_number'], unique=False)
    op.create_index(op.f('ix_dim_stores_hibuddy_slug'), 'dim_stores', ['hibuddy_slug'], unique=False)
    op.create_index(op.f('ix_dim_stores_hibuddy_store_id'), 'dim_stores', ['hibuddy_store_id'], unique=False)
    op.create_table('fct_ocs_launches',
    sa.Column('launch_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ocs_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('launch_id')
    )
    op.create_index(op.f('ix_fct_ocs_launches_category'), 'fct_ocs_launches', ['category'], unique=False)
    op.create_index(op.f('ix_fct_ocs_launches_launch_date'), 'fct_ocs_launches', ['launch_date'], unique=False)
    op.create_index(op.f('ix_fct_ocs_launches_product_id'), 'fct_ocs_launches', ['product_id'], unique=False)
    op.create_table('fct_price_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('scraped_date', sa.Date(), nullable=False),
    sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['dim_stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id'),
    sa.UniqueConstraint('store_id', 'product_id', 'scraped_date', name='uq_fct_price_history_grain')
    )
    op.create_index(op.f('ix_fct_price_history_product_id'), 'fct_price_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_fct_price_history_scraped_date'), 'fct_price_history', ['scraped_date'], unique=False)
    op.create_index(op.f('ix_fct_price_history_store_id'), 'fct_price_history', ['store_id'], unique=False)
    op.create_table('fct_prices',
    sa.Column('fact_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('scraped_date', sa.Date(), nullable=True),
    sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('typical_nearby', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('promo_first_seen', sa.Date(), nullable=True),
    sa.Column('promo_last_seen', sa.Date(), nullable=True),
    sa.Column('promo_duration_days', sa.Integer(), sa.Computed('(promo_last_seen - promo_first_seen)', persisted=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['dim_stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('store_id', 'product_id', name='uq_fct_prices_store_product')
    )
    op.create_index(op.f('ix_fct_prices_product_id'), 'fct_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_fct_prices_scraped_date'), 'fct_prices', ['scraped_date'], unique=False)
    op.create_index(op.f('ix_fct_prices_store_id'), 'fct_prices', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fct_prices_store_id'), table_name='fct_prices')
    op.drop_index(op.f('ix_fct_prices_scraped_date'), table_name='fct_prices')
    op.drop_index(op.f('ix_fct_prices_product_id'), table_name='fct_prices')
    op.drop_table('fct_prices')
    op.drop_index(op.f('ix_fct_price_history_store_id'), table_name='fct_price_history')
    op.drop_index(op.f('ix_fct_price_history_scraped_date'), table_name='fct_price_history')
    op.drop_index(op.f('ix_fct_price_history_product_id'), table_name='fct_price_history')
    op.drop_table('fct_price_history')
    op.drop_index(op.f('ix_fct_ocs_launches_product_id'), table_name='fct_ocs_launches')
    op.drop_index(op.f('ix_fct_ocs_launches_launch_date'), table_name='fct_ocs_launches')
    op.drop_index(op.f('ix_fct_ocs_launches_category'), table_name='fct_ocs_launches')
    op.drop_table('fct_ocs_launches')
    op.drop_index(op.f('ix_dim_stores_hibuddy_store_id'), table_name='dim_stores')
    op.drop_index(op.f('ix_dim_stores_hibuddy_slug'), table_name='dim_stores')
    op.drop_index(op.f('ix_dim_stores_agco_licence_number'), table_name='dim_stores')
    op.drop_table('dim_stores')
    op.drop_index(op.f('ix_dim_products_normalized_name'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_normalized_brand'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_category'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_brand'), table_name='dim_products')
    op.drop_table('dim_products')
    # ### end Alembic commands ###
